name: sam2_mps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.3.1
  - torchvision>=0.18.1
  - numpy>=1.24.4
  - tqdm>=4.66.1
  - hydra-core>=1.3.2
  - iopath>=0.1.10
  - pillow>=9.4.0
  - matplotlib>=3.9.1
  - pip
  - pip:
    - opencv-python>=4.7.0
    - -e .